// packages/react/src/components/progress.tsx
import React from 'react';
import type { ProgressComponentProps } from '../types';
import { classNames } from '../utils/classnames';
import { Bar } from './bar';
import { Peg } from './peg';
import { Spinner } from './spinner';
import { SpinnerIcon } from './spinner-icon';

export type ProgressProps<T extends React.ElementType = 'div'> = Omit<
  ProgressComponentProps<T>,
  'classSelector'
>;

function ProgressInner<T extends React.ElementType = 'div'>(
  { as, children, className, style, ...rest }: ProgressProps<T>,
  ref: React.ForwardedRef<React.ComponentRef<T>>,
) {
  const Component = as ?? ('div' as T);
  return React.createElement(
    Component,
    {
      ref,
      className: classNames('bprogress', className),
      style: { ...style, display: 'none' } as React.CSSProperties,
      ...(rest as React.ComponentPropsWithoutRef<T>),
    },
    children || (
      <>
        <Bar>
          <Peg />
        </Bar>
        <Spinner>
          <SpinnerIcon />
        </Spinner>
      </>
    ),
  );
}

export const Progress = React.forwardRef(ProgressInner) as <
  T extends React.ElementType = 'div',
>(
  props: ProgressProps<T> & { ref?: React.ForwardedRef<React.ComponentRef<T>> },
) => ReturnType<typeof ProgressInner>;

// packages/vue/src/components/progress.vue
<template>
  <component
    :is="is || 'div'"
    v-bind="attrs"
    :class="computedClass"
    :style="computedStyle"
  >
    <slot>
      <Bar>
        <Peg />
      </Bar>
      <Spinner>
        <SpinnerIcon />
      </Spinner>
    </slot>
  </component>
</template>

<script setup lang="ts">
import { computed, ComputedRef, CSSProperties, useAttrs } from 'vue';
import Bar from './bar.vue';
import Peg from './peg.vue';
import Spinner from './spinner.vue';
import SpinnerIcon from './spinner-icon.vue';
import { classNames } from '../utils/classnames';
import type { ProgressProps } from '../types';

const props = defineProps<ProgressProps>();
const attrs = useAttrs();

// Concatenates the default 'bprogress' class with any class passed as prop.
const computedClass = computed(() => {
  return classNames('bprogress', props.class);
});

// Adds “display: none” to existing style
const computedStyle: ComputedRef<CSSProperties | string> = computed(() => {
  if (typeof props.style === 'string') {
    return props.style + '; display: none;';
  } else if (typeof props.style === 'object' && props.style !== null) {
    return { ...props.style, display: 'none' };
  }
  return { display: 'none' };
});
</script>
